### ISSUE TITLE
YAML-based specification of aospy objects

### ISSUE THREAD

**Issue by spencerahill** [spencerahill/aospy#333]
In starting to play around with intake (motivated by #318), which uses yaml files to specify data catalogs, it occurred to me that we could reduce boilerplate and thus make aospy more user-friendly by supporting aospy objects being defined as yaml files rather than as python modules.

For example, I believe it would be much less intimidating for a new user to be able to create a "my-aospy-lib.yaml" file comprising

```
my_aospy_proj:
  type: proj
  name: my-cool-proj
  description: My very first aospy project
  direc_out: /path/to/my/files

[...]
precip:
  type: var
  name: precip
  [...]

```
to create their aospy objects instead of a "my_aospy_lib.py" file comprising
```python
from aospy import Proj, Var

my_aospy_proj = Proj(
    'my-cool-proj', 
    description="My very first aospy project",
    direc_out="/path/to/my/files",
)
[...]
```

Then they don't have to worry about getting the Python syntax right, dealing with imports, and so on.

The devil may well be in the details, but I think implementing the core of this would actually be quite straightforward, just using [pyyaml](https://pyyaml.org/wiki/PyYAMLDocumentation); then it's ```yaml.safe_load(open("my_aospy_proj.yaml"))``` to get a nested dictionary that we could then turn into aospy objects.

I may take a stab at this, although I'd be keen to know if folks see any obvious pitfalls or drawbacks.
